### ISSUE TITLE
VIdeos autoplaying

### ISSUE THREAD

**Issue by Matthewus** [ParticleCore/Particle#82]
Hi! Some of the videos started autoplaying even though i did not change the settings. I tried to reset the settings and even reinstall the addon but the problem is still present. Some videos still do not autoplay. What can i do to find what causes the problem? I can see cross origin requests being blocked in the browser console, but i don't know what that means.

**Comment by ParticleCore** [comment]
I don't understand what is the problem, you mention that they autoplay and that they still do not autoplay.

Alos provide more details: https://github.com/ParticleCore/Particle/wiki/Report-a-problem

**Comment by Matthewus** [comment]
Browser Name: Firefox

Browser Version: 40.0.3

Operating System: Windows 7

Software Type: Add-on

Software Version: 0.5.8

Problem Description:  Some videos autoplaying when Autoplay videos is not checked.
This autoplays: https://www.youtube.com/watch?v=0wdqF5zGQ_c
This is not: https://www.youtube.com/watch?v=librIpBUJxU
Expected behavior: videos shouldn't autoplay.
Problem is present with the userscript version too. All other settings work fine.
Steps to reproduce: 
-
Additional details: 
I disabled all other extensions, reinstalled YouTube Plus but the problem is still present.

**Comment by ParticleCore** [comment]
This is very strange, it does not autoplay here with the add-on and userscript versions. Can you share your settings?

**Comment by Matthewus** [comment]
{
  "GEN_BTTR_NTF": false,
  "GEN_SUB_LIST": false,
  "GEN_INF_SCRL": false,
  "GEN_BLUE_GLOW": false,
  "GEN_SDBR_ON": false,
  "VID_END_SHRE": false,
  "VID_DFLT_QLTY": "hd720",
  "VID_PLST_SEP": false,
  "VID_PLST_ATPL": true,
  "VID_PLST_RVRS": false,
  "VID_PLR_ALVIS": false,
  "VID_PLR_SIZE_MEM": false,
  "VID_PLR_DYN_SIZE": false,
  "VID_PLR_FIT_WDTH": "1280px",
  "VID_HIDE_COMS": "0",
  "VID_POST_TIME": false,
  "VID_VID_CNT": false,
  "VID_DESC_SHRT": false,
  "VID_SDBR_ALGN": "0",
  "BLK_ON": false,
  "volLev": 50,
  "plApl": false,
  "plRev": false,
  "advOpts": false,
  "blacklist": {},
  "GEN_HDE_CHN_SDBR": false,
  "GEN_HDE_SRCH_SDBR": false,
  "GEN_HDE_RECM_SDBR": false,
  "GEN_HIDE_FTR": false,
  "GEN_CMPT_TTLS": false,
  "GEN_DSB_HVRC": false,
  "GEN_GRID_SRCH": false,
  "GEN_GRID_SUBS": false,
  "GEN_CHN_DFLT_PAGE": "default",
  "GEN_SPF_OFF": false,
  "GEN_REM_APUN": false,
  "GEN_YT_LOGO_LINK": false,
  "GEN_DSBL_ADS": false,
  "VID_LAYT_AUTO_PNL": false,
  "VID_HIDE_DETLS": false,
  "VID_TTL_CMPT": false,
  "VID_PLR_FIT": false,
  "VID_PLR_INFO": false,
  "VID_PLR_DASH": false,
  "VID_VOL_WHEEL": false,
  "VID_PLR_ALACT": false,
  "VID_PLR_VOL_MEM": false,
  "VID_PLR_ANTS": true,
  "VID_PLR_CC": false,
  "VID_PLR_ATPL": false,
  "VID_SUB_ADS": false,
  "VID_PLR_ADS": false
}

**Comment by ParticleCore** [comment]
Just tried with your settings, the video does not Autoplay.

When the videos autoplay does their link show something like "t=X"? (X is any number)

Because this is a code that forces the video to play at that specific time, for example this is the video you previously said that didn't autoplay will play once you open it because of that time code:

https://www.youtube.com/watch?v=librIpBUJxU#t=32

**Comment by Matthewus** [comment]
No, i do not have any time code at the end of the link.

**Comment by ParticleCore** [comment]
Then the issue might be related a browser setting. To rule this out create a new profile and install just YouTube + and see if the video still autoplays with autoplay disabled.

To use Firefox with a new profile follow these instructions: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_starting-the-profile-manager

**Comment by Matthewus** [comment]
I think i found the cause of the problem. Previously i forgot to disable Noscript, and now that i did, your extension works fine. I was able to reproduce the problem in a clean profile installing Noscript and YouTube Plus using the default settings in both and this video: https://www.youtube.com/watch?v=0wdqF5zGQ_c

**Comment by ParticleCore** [comment]
Thank you for being so patient and letting me know what the cause was. I assume that this is now solved then, if you need anything else just let me know.

**Comment by Matthewus** [comment]
It is not solved, because i would like to use Noscript. Can you reproduce the issue? If you cannot i will contact the Noscript developer.

**Comment by ParticleCore** [comment]
YT+ is a script itself, it needs to be allowed to run in YouTube for it to work and it also depends on other scripts that are present in the YouTube website. Is the Noscript active for YouTube?

**Comment by ParticleCore** [comment]
I have installed Noscript and I am using it with your default settings, I am able to replicate the problem now, will try to see if it is something I can fix or not.

**Comment by Matthewus** [comment]
With my Noscript list and also with the default list the problem is present. In my list only doubleclick.net and googleadservices.com are disabled.

**Comment by ParticleCore** [comment]
I think I might have found a possible conflict. In YT+ go to the settings > Video > Player settings and enable `Disable advertisements in the video page`. Refresh the page and see if the video still autoplays.

**Comment by Matthewus** [comment]
Now its good. I unchecked that option because i already use ublock origin and noscipt.

**Comment by ParticleCore** [comment]
For some reason when that option is disabled it causes the rest of YT+ to not work if the user also has Noscript installed. Will continue debugging to see what is the main cause.

**Comment by ParticleCore** [comment]
Set the previous YT+ setting to how it was when the video was autoplaying, then in Noscript click "Allow doubleclick.net". Refresh and see if the video still autoplays.

**Comment by ParticleCore** [comment]
After further testing it seems that Noscript is interfering with the player autoplay function by blocking the before mentioned script. For now the solutions are either to enable the YT+ option I mentioned before or allow doubleclick.net in Noscript.

I am sorry but I can't find a way to fix this from YT+.

**Comment by Zarggg** [comment]
Out of curiosity, what script in particular from doubleclick.net is interfering with YT+? Just a generic ad loader?

**Comment by ParticleCore** [comment]
It is not interfering with YT+, but with the YouTube player itself. Seems like there are certain conditions in the player which depend on the doubleclick response/fetch which if not met or stays stalled then the autoplay functionality does not work properly. So far this only happens with videos that contain advertisement.

**Comment by Matthewus** [comment]
https://greasyfork.org/en/scripts/593-yays-yet-another-youtube-script This script uses a different method to disable autoplay? Because this works wiith Noscript blocking doubleclick.

**Comment by ParticleCore** [comment]
@Matthewus That is correct, YAYS does not make use of the default player functions to control its playback initialization, instead it stops the video after it starts playing (but this happens so fast that it looks like it never started).

While it might seem to work for this purpose, it has (or had, last time I checked) a few side effects; sporadic player errors, conflicts while in fullscreen and while playing playlists, increase in memory usage and relies on a function that might be removed by YouTube without notice.

**Comment by ganego** [comment]
> I think I might have found a possible conflict. In YT+ go to the settings > Video > Player settings and enable Disable advertisements in the video page. Refresh the page and see if the video still autoplays.

Oh wow, thanks for that. I was really annoyed that nearly every video started autoplaying.
You should maybe write that info somwhere on your github page and write something in the settings for this option (and/or the "stop autoplay" option) to tell users to enable it when NS is installed to make the "stop autoplay" function works.

btw, sorry to hear that stuff with AMO, but they will fuck up their addon system anyway (and thus destroying FF) in some versions and you would have had to re-code your whole addon anyway.
